# Generated by Django 3.2.9 on 2022-04-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0004_tranfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Acount',
        ),
    ]
