# Generated by Django 3.2.9 on 2022-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0005_remove_account_acount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
