# Generated by Django 3.2.9 on 2022-04-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0006_alter_tranfer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranfer',
            name='sending_user',
        ),
    ]
