# Generated by Django 3.2.9 on 2022-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0007_remove_tranfer_sending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranfer',
            name='recieving_user',
            field=models.CharField(max_length=30),
        ),
    ]
