# Generated by Django 3.2.9 on 2022-04-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0008_alter_tranfer_recieving_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
