# Generated by Django 3.2.9 on 2022-06-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0009_alter_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='conditions',
            new_name='reason',
        ),
    ]
