# Generated by Django 3.2.9 on 2022-06-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0010_rename_conditions_borrower_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='reason',
            new_name='purpose',
        ),
    ]
