# Generated by Django 3.2.9 on 2022-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0011_rename_reason_borrower_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
