# Generated by Django 3.2.9 on 2022-11-16 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0012_account_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.borrower')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.lender')),
            ],
        ),
    ]
