# Generated by Django 3.2.9 on 2022-11-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0013_latestdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestDB',
        ),
    ]
