# Generated by Django 3.2.9 on 2022-11-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0017_appyloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user2',
            new_name='apply',
        ),
    ]
