# Generated by Django 3.2.9 on 2022-12-10 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_system', '0018_rename_user2_account_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_system.applyloan')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='main_system.account')),
            ],
        ),
    ]
