# Generated by Django 3.2.9 on 2022-12-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0020_alter_applyloan_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='user',
            new_name='lendname',
        ),
    ]
