# Generated by Django 3.2.9 on 2022-12-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0021_rename_user_lender_lendname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='lendname',
            new_name='user',
        ),
    ]
