# Generated by Django 3.2.9 on 2023-01-09 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0027_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Level',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
