# Generated by Django 3.2.9 on 2023-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0029_verificaton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
